name: CI-DEV
on: [workflow_dispatch]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out code
        uses: actions/checkout@v3
      - name: switch to project folder
        run: |
          cd LayingFoundation
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Package
        run: |
          cd LayingFoundation
          npm install
      - name: Build Project
        run: |
          cd LayingFoundation
          npm run build
      - name: Build dev Project
        run: |
          cd LayingFoundation
          npm start
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LayingFoundation v1
          path: LayingFoundation/dist
          if-no-files-found: error
